### ISSUE TITLE
Traceback during extraction

### ISSUE THREAD

**Issue by pand0rausa** [HarmJ0y/ImpDump#5]
When running impdump and pointing to the SYSTEM and output files it immediately returns this error.

Traceback (most recent call last):
  File "impdump.py", line 246, in <module>
    decKrbtgt(sys.argv[1], sys.argv[2])
  File "impdump.py", line 145, in decKrbtgt
    print decUserHash(bootkey, rawPekKey, "krbtgt", rawRID, "", rawNTLMhash)
  File "impdump.py", line 32, in decUserHash
    rid = int(rawRID[48:],16)
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by quentinhardy** [comment]
Same error. I think the **bug is in _extract.sh_**.

This error shows the Encrypted PEK (Password Encryption Key) is not correctly extracted from ntds file with _extract.sh_.

The output file of _extract.sh_ **doesn't contain ATTk590689 attributes** in my case.

_impdump.py_ uses the output file of extract.sh script for getting hashes.
_impdump.py_ needs this value for decrypting hashes (PEK + RC4).

So I think It is impossible to extract hashes for us with this project...
